<?php
$error["en-US"] = array( "INVALID_RPC" => "INVALID FUNCTION CALL",
						 "INVALID_PARAMS" => "INVALID PARAMS",
						 "INVALID_TITLE" => "INVALID TITLE",
						 "INVALID_DESC" => "INVALID DESCRIPTION",
						 "INVALID_CONTENT" => "INVALID OR NO CONTENT",
						 "INVALID_DB_RESULT" => "CANNOT SAVE, PLEASE CONTACT US",
						 "INVALID_ID" => "INVALID ID"
						);
